
services:
  mysql:
    image: mysql:9.2
    container_name: book-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_management_db
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - book-management-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: book-management-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpass
      JAVA_OPTS: "-XX:+UseZGC -XX:+UnlockExperimentalVMOptions -Xms512m -Xmx1024m"
    ports:
      - "8080:8080"
    networks:
      - book-management-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    volumes:
      - app_logs:/app/logs

volumes:
  mysql_data:
    driver: local
  app_logs:
    driver: local

networks:
  book-management-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16